import { adminDb } from './firebase-admin';
import { GoogleGenAI } from "@google/genai";

export async function runAutoPostBot() {
  console.log('[Bot Logic] Starting runAutoPostBot...');
  const startTime = Date.now();
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not found in environment');
  }

  console.log('[Bot Logic] Triggering Gemini generation...');
  const ai = new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  const prompt = `Generate a breaking news story about the Zambian music scene. 
  Focus on a fictitious but realistic new song release, artist collaboration, or upcoming major concert in Lusaka. 
  Include a 'headline' and 'content' (3-4 paragraphs). 
  Format the response exactly as a JSON object with keys 'headline' and 'content'.`;

  const geminiStart = Date.now();
  const response = await ai.models.generateContent({
    model: "gemini-1.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
    }
  });
  console.log(`[Bot Logic] Gemini response received in ${Date.now() - geminiStart}ms`);

  const text = response.text;
  if (!text) throw new Error('Gemini returned an empty response');
  let newsData;
  try {
    const cleanText = text.replace(/```json\n?|```/g, '').trim();
    newsData = JSON.parse(cleanText);
  } catch (e) {
    console.error('[Bot Logic] JSON parse error:', text);
    throw new Error('Gemini returned an invalid JSON format');
  }

  const seeds = ['music', 'concert', 'studio', 'artist', 'stage', 'microphone', 'guitar', 'drums', 'afrobeats', 'rap'];
  const randomSeed = seeds[Math.floor(Math.random() * seeds.length)];
  const imageUrl = `https://picsum.photos/seed/${randomSeed}-${Date.now()}/1200/800`;

  const botPost = {
    headline: newsData.headline,
    content: newsData.content,
    featuredImage: imageUrl,
    userId: 'system-auto-bot',
    createdAt: new Date(),
    updatedAt: new Date(),
    isAutoGenerated: true
  };

  const dbStart = Date.now();
  const docRef = await adminDb.collection('news').add(botPost);
  console.log(`[Bot Logic] Successfully published news in ${Date.now() - dbStart}ms:`, docRef.id);
  console.log(`[Bot Logic] Total bot execution time: ${Date.now() - startTime}ms`);

  return {
    id: docRef.id,
    post: newsData
  };
}
