import { adminDb } from './firebase-admin';
import { GoogleGenAI } from "@google/genai";

export async function runAutoPostBot() {
  const apiKey = process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not found in environment');
  }

  console.log('[Bot Logic] Triggering Gemini generation...');
  const ai = new GoogleGenAI(apiKey);
  const model = ai.getGenerativeModel({ model: "gemini-1.5-flash" });

  const prompt = `Generate a breaking news story about the Zambian music scene. 
  Focus on a fictitious but realistic new song release, artist collaboration, or upcoming major concert in Lusaka. 
  Include a 'headline' and 'content' (3-4 paragraphs). 
  Format the response exactly as a JSON object with keys 'headline' and 'content'.`;

  const response = await model.generateContent({
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    generationConfig: {
      responseMimeType: "application/json",
    }
  });

  const rawText = response.response.text();
  let newsData;
  try {
    const cleanText = rawText.replace(/```json\n?|```/g, '').trim();
    newsData = JSON.parse(cleanText);
  } catch (e) {
    console.error('[Bot Logic] JSON parse error:', rawText);
    throw new Error('Gemini returned an invalid JSON format');
  }

  const seeds = ['music', 'concert', 'studio', 'artist', 'stage', 'microphone', 'guitar', 'drums', 'afrobeats', 'rap'];
  const randomSeed = seeds[Math.floor(Math.random() * seeds.length)];
  const imageUrl = `https://picsum.photos/seed/${randomSeed}-${Date.now()}/1200/800`;

  const botPost = {
    headline: newsData.headline,
    content: newsData.content,
    featuredImage: imageUrl,
    userId: 'system-auto-bot',
    createdAt: new Date(),
    updatedAt: new Date(),
    isAutoGenerated: true
  };

  const docRef = await adminDb.collection('news').add(botPost);
  console.log('[Bot Logic] Successfully published news:', docRef.id);

  return {
    id: docRef.id,
    post: newsData
  };
}
